import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    marginTop: 50,
    marginHorizontal: 26,
  },
  title: {
    fontSize: 35,
    color: "#F7BF29",
    fontWeight: "bold",
    marginBottom: 42,
  },
  containerTitle: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginBottom: 4,
  },
  star: {
    width: 25,
    height: 26,
    marginTop: 8,
    marginLeft: 50,
  },
  number: {
    fontSize: 30,
    color: "#FE720C",
    fontWeight: "bold",
  },
  itens: {
    backgroundColor: "#FFF",
    borderColor: "#606060",
    borderWidth: 0.2,
    borderRadius: 12,
    width: 360,
    height: 80,
    marginBottom: 14,
  },
  containerBold: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginHorizontal: 12,
    marginTop: 8,
  },
  textBold: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#606060",
  },
  textNumber: {
    marginRight: 5,
    fontSize: 24,
    fontWeight: "bold",
    color: "#606060",
  },
  containerText: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginHorizontal: 12,
    marginBottom: 13,
  },
  text: {
    fontSize: 14,
    color: "#979797",
  },
  textPts: {
    fontSize: 19,
    color: "#979797",
    fontWeight: "bold",
  },
  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#979797",
    opacity: 0.8,
  },
  modalView: {
    width: 412,
    height: 364,
    marginTop: 461,
    backgroundColor: "#FFF",
    borderRadius: 17,
    alignItems: "center",
    paddingHorizontal: 29,
  },

  buttonClose: {
    flexDirection: "row",
    width: 161,
    height: 52,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFC225",
  },
  textStyle: {
    color: "white",
    fontWeight: "bold",
    textAlign: "center",
    paddingLeft: 8,
  },
  text: {
    fontSize: 17,
    fontWeight: "bold",
    color: "#979797",
    textAlign: "center",
    marginBottom: 6,
  },
  pontos: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#FE720C",
    marginBottom: 10,
  },
  cancelar: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#F7BF29",
    marginTop: 10,
  },
  modalText: {
    marginBottom: 15,
    textAlign: "center",
    color: "#606060",
    fontSize: 26,
    fontWeight: "bold",
  },
  line: {
    width: 45,
    height: 5,
    backgroundColor: "#979797",
    marginTop: 9,
    marginBottom: 19,
  },
});
