import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    marginTop: 50,
    marginHorizontal: 26,
  },
  title: {
    fontSize: 35,
    color: "#F7BF29",
    fontWeight: "bold",
  },
  containerTitle: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  cog: {
    width: 25,
    height: 26,
    marginTop: 8,
    marginLeft: 50,
  },
  user: {
    alignItems: "center",
    zIndex: 1,
  },
  userContainer: {
    width: 350,
    height: 157,
    marginTop: -60,
    borderWidth: 0.2,
    borderRadius: 15,
  },
  nameUser: {
    fontSize: 24,
    textAlign: "center",
    fontWeight: "bold",
    marginTop: 60,
  },
  itensContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    borderTopWidth: StyleSheet.hairlineWidth,
    marginTop: 10.5,
  },
  medalha: {
    flexDirection: "row",
    marginTop: 15.5,
    color: "#FE9E0C",
  },
  line: { borderRightWidth: StyleSheet.hairlineWidth },
  text: {
    color: "#FE9E0C",
    fontSize: 19,
    fontWeight: "bold",
    marginLeft: 4,
  },
  medal: {
    marginLeft: 50,
  },
  number: {
    color: "#FE720C",
    fontSize: 19,
    fontWeight: "bold",
    marginBottom: 8,
    marginLeft: 4,
    marginRight: 50,
  },
  containerApadrinhados: {
    width: 350,
    height: 116,
    marginTop: 13,
    borderWidth: 0.2,
    borderRadius: 15,
  },
  tituloApadrinhados: {
    fontWeight: "bold",
    fontSize: 20,
    paddingLeft: 24,
    marginTop: 16,
    marginBottom: 4,
    color: "#F7BF29",
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  imgApadrinhados: {
    width: 55,
    height: 55,
    marginRight: 7,
  },
  containerImgApadrinhados: {
    flexDirection: "row",
    marginLeft: 24,
  },
  containerPlacar: {
    width: 350,
    height: 295,
    marginTop: 13,
    borderWidth: 0.2,
    borderRadius: 15,
  },
  tituloPlacar: {
    fontSize: 20,
    fontWeight: "bold",
    paddingTop: 19,
    paddingBottom: 4,
    paddingLeft: 24,
    borderBottomWidth: StyleSheet.hairlineWidth,
    color: "#F7BF29",
  },
  texto: {
    fontSize: 20,
    fontWeight: "bold",
    paddingTop: 19,
    paddingBottom: 13,
    paddingLeft: 24,
    borderBottomWidth: StyleSheet.hairlineWidth,
    color: "#979797",
  },
  userText: {
    fontSize: 20,
    fontWeight: "bold",
    paddingTop: 19,
    paddingBottom: 13,
    paddingLeft: 24,
    borderBottomWidth: StyleSheet.hairlineWidth,
    color: "#FE720C",
  },
});
